Mencari matrix A

In [ ]:
import numpy as np

L = np.array([[2, 0, 0],
              [3, 1, 0],
              [3, 4, 1]])

U = np.array([[1, 2, 5],
              [0, 1, 3],
              [0, 0, 1]])
A = np.dot(L, U)

print("Matriks A:")
print(A)

Matriks A:
[[ 2  4 10]
 [ 3  7 18]
 [ 3 10 28]]


matriks X

In [ ]:
b = np.array([11, 7, 2])

# membuat matriks x
x = np.zeros(3)  # Membuat matriks x awal dengan nol

# x3
x[2] = b[2] / U[2, 2]

# x2
x[1] = (b[1] - U[1, 2] * x[2]) / U[1, 1]

# dan x1
x[0] = (b[0] - U[0, 1] * x[1] - U[0, 2] * x[2]) / U[0, 0]

# ini untuk menampilkan x [x1, x2, x3]
print("x:")
print(x)

x:
[-1.  1.  2.]

Mencari Y

In [ ]:

#sama kyk cari X, cuma kalo Y diputer balik
b = np.array([2, 5, 8])
y = np.zeros(3)
y[0] = b[0] / L[0, 0]
y[1] = (b[1] - L[1, 0] * y[0]) / L[1, 1]
y[2] = (b[2] - L[2, 0] * y[1] - L[1, 0] * y[0]) / L[2, 2]
print("y:")
print(y)

y:
[ 1.  2. -1.]